Path completion
vigoux/complementree.nvim pull request #2
Opened 2021-12-14 09:50 UTC by sunjon

Recursive path completion, RFC. Lots of rough edges, tried to avoid  dependencies for path and scandir functions.

2021-12-14 09:59 UTC, vigoux reviewed
It looks definitely great, thank you very much for that !

2021-12-14 09:59 UTC, vigoux commented on lua/complementree/filters.lua
> +  return w:find(prefix, 1, true) ~= nil
You can remove the `~= nil` here I think ?

2021-12-14 09:59 UTC, vigoux commented on lua/complementree/utils.lua
> +local os_sep = get_os_file_separator()
As you do that only once, maybe avoid the function call and set `os_sep` correctly directly ?

2021-12-14 09:59 UTC, vigoux commented on lua/complementree/sources.lua
> +  local MAKE_RELATIVE = true
Maybe turn the `filepath` function into a function that returns a source, and use the parameters of the outer function to configure the inner function ?

2021-12-15 08:45 UTC, sunjon commented
I'm testing it with a setup like this:
```lua
local fp_source = sources.create_filepath_source {
  max_depth = 3,
  root_dirs = { "/home/sunjon" },
  match_patterns = { "%.png$", "%.jpg$" }
}
local path_completion = combine.pipeline(fp_source, filter.substr, sorter.alphabetic)
```

2021-12-15 08:49 UTC, vigoux commented on lua/complementree/sources.lua
> +M.create_filepath_source = function(opts)
I think that we should keep `filepath_matches` for consistency here.

2021-12-15 08:49 UTC, vigoux commented on lua/complementree/sources.lua
> +  local src = function(_, _, _, _)
Why not `return function...` here ?

2021-12-15 08:49 UTC, vigoux commented on lua/complementree/sources.lua
> +  local src = function(_, _, _, _)
And I think that this can be cached too ?

2021-12-15 09:02 UTC, vigoux commented on lua/complementree/sources.lua
> +M.filepath = M.create_filepath_matches()
This should go into the `defaults.lua` and be of the form `M.filepath = pipeline(..., substr)` and such.

2021-12-15 09:02 UTC, vigoux commented on lua/complementree/sources.lua
> +M.create_filepath_matches = function(opts)
I would really like this like so:
```suggestion
M.filepath_matches = function(opts)
```

2021-12-15 09:29 UTC, vigoux requested changes

2021-12-15 09:29 UTC, vigoux commented on lua/complementree/defaults.lua
> +M.filepath = comb.pipeline(sources.filepath_matches, filters.substr, comp.alphabetic)
```suggestion
M.filepath = comb.pipeline(sources.filepath_matches(), filters.substr, comp.alphabetic)
```

2021-12-15 10:04 UTC, vigoux reviewed
Could you add some tests for the substr filter ?

2021-12-16 17:26 UTC, sunjon commented
Closing in favor of https://github.com/vigoux/complementree.nvim/pull/4

2021-12-16 17:26 UTC, closed without merging